<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Dashboard</title>

    <link rel="stylesheet" href="/css/common.css">
    <link rel="stylesheet" href="/css/dashboard.css">

    <script src="/js/main.js"></script>
</head>
<body>
    <div id="dashboard" class="to-table">

        <div id="sidebar" class="valign-top">
            <div class="to-table logo">
                <div>Dash<span>Logo</span></div>
            </div>
            <ul class="menu">
                <li><a href="/register">Register</a></li>
                <li><a href="/signin">Sign In</a></li>
                <li><a href="/signout">Logout</a></li>
                <li><a href="#">Menu item</a></li>
                <li><a href="#">Menu item</a></li>
                <li><a href="#">Menu item</a></li>
            </ul>
        </div>

        <div id="content" class="valign-top">
            <?php echo $this->getContent(); ?>
        </div>

    </div>
</body>
</html>
