<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Login</title>

    <link rel="stylesheet" href="/css/common.css">
    <link rel="stylesheet" href="/css/login.css">

    <script src="/js/main.js"></script>
    <script src="/js/login.js"></script>
</head>
<body>

<div id="login">

    <div id="content">
        <?php echo $this->getContent(); ?>
    </div>

</div>

<div id="copy">
    <div class="text-center">
        <small>Made by <a href="http://">NoName2</a></small></div>
</div>


</body
</html>
