<div class="top-navigation to-table">
    <div>Dashboard</div>
    <div class="text-right">
        <span>You login as <a href="" class="user"><?= $user['username']; ?></a></span>
        <a href="" class="ico">L</a>
        <a href="" class="ico">M</a>
        <a href="" class="ico">Z</a>
    </div>
</div>
<div class="container">
    <div class="card">

        <h2><?=$welcome; ?></h2>

    </div>
</div>