
<div class="columns text-center">

    <h1> Register </h1>

    <div data-ui="form" class="form-sign-in card text-left">
        <form method="post">

            <div class="form-row">
                <label>Username
                    <input data-input="username" class="input" type="text" name="username" placeholder="username" />
                </label>
            </div>

            <div class="form-row">
                <label>Email
                    <input data-input="email" class="input" type="text" name="email" placeholder="email" />
                </label>
            </div>

            <div class="form-row">
                <label>Password
                    <input data-input="password" class="input" type="password" name="password" placeholder="password" />
                </label>
            </div>

            <div class="form-row">
                <label>Confirm Password
                    <input data-input="passwordConfirm" class="input" type="password" name="password" placeholder="password" />
                </label>
            </div>

            <div class="form-row">
                <div class="to-table">
                    <div class="">
                        <a href="/signin" class="button">Sign In</a>
                    </div>
                    <div class="text-right">
                        <button data-btn="submit" class="button">Register</button>
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div data-ui="info" class="info text-center"></div>
            </div>

        </form>
    </div>

</div>
