
<div class="columns text-center">

    <h1> Login </h1>

    <div class="notice">Demo login is <strong>guest</strong>, password <strong>12345</strong></div>

    <div data-ui="form" class="form-sign-in card text-left">
        <form method="post">

            <div class="form-row">
                <label>Username
                    <input data-input="username" class="input" type="text" name="username" placeholder="username" />
                </label>
            </div>

            <div class="form-row">
                <label>Password
                    <input data-input="password" class="input" type="password" name="password" placeholder="password" />
                </label>
            </div>

            <div class="form-row">
                <div class="to-table">
                    <div class="">
                        <a href="/register" class="button">Register</a>
                    </div>
                    <div class=" text-right">
                        <button data-btn="submit" class="button">Sign In</button>
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div data-ui="info" class="info text-center"></div>
            </div>

        </form>
    </div>

</div>
